#!/usr/bin/env python

from itertools import product

def build(ctx):
    data = ctx.path.ant_glob('*.json')
    if data:
        ctx(features='run_r_plot',
            source=['imm-strong-scaling.r'],
            data=ctx.path.ant_glob('*.json'),
            target=['imm-strong-scaling.pdf'])
