#!/usr/bin/env python

from waflib import Logs

def build(ctx):
    if not ctx.env.RCMD:
        Logs.warn("No plots will be generated")
        return

    ctx.recurse('hc-strong-scaling')
    ctx.recurse('imm-strong-scaling')
